export const copy = {
  brand: "ArchiveDiver",
  eyebrow: "Smithsonian Exhibit Builder",
  heroTitle: "Build a small digital exhibit from a historical thread.",
  heroBody:
    "Shape a topic into a readable exhibit with Smithsonian objects, source facts, and generated framing copy.",
  topicLabel: "Topic",
  topicPlaceholder: "Apollo program, Harlem Renaissance, Dust Bowl...",
  periodLabel: "Time Period",
  countLabel: "Artifact Count",
  buildLabel: "Dive for Artifacts",
  loadingLabel: "Diving…",
  exhibitLabel: "Generated Exhibit",
  artifactsLabel: "Artifacts",
  featuredLabel: "Featured Artifact",
  timelineLabel: "Timeline",
  noTimeline: "No structured dates were available for this result set.",
  emptyArtifacts: "No image-bearing artifacts were returned for this search.",
  emptyArtifactsBody:
    "The backend returned an exhibit frame, but no artifacts with usable images made it through the source filters.",
  devLabel: "Dev Details",
  devHint: "Trace and limitations",
  noLimitations: "No limitations reported.",
  noToolCalls: "No tool calls recorded.",
  sourceLabel: "Source",
  sourceLinkLabel: "View at Smithsonian",
  rightsLabel: "Rights",
  objectTypeLabel: "Object type",
  creatorLabel: "Creator",
  museumLabel: "Museum",
  dateLabel: "Date",
  resultNotesLabel: "Result notes",
  weakResultsCountNote: "Fewer image-bearing artifacts were returned than requested.",
  weakResultsTimelineNote: "Timeline coverage is sparse because structured dates were unavailable.",
  weakResultsCaptionNote: "Some generated captions were missing, so those cards fall back to source facts only.",
  emptyStateTitle: "Your exhibit will assemble here.",
  emptyStateBody:
    "Pick a topic, set a period if you want, and build an exhibit panel with artifacts, metadata, and a readable narrative frame.",
  loadingStateTitle: "Building exhibit…",
  loadingStateBody:
    "Pulling source objects and shaping the panel. Existing results stay in place until the next exhibit is ready.",
  errorPrefix: "Unable to build exhibit:",
  imageFallbackLabel: "Image unavailable",
} as const;

export const periodOptions = [
  { label: "Any", value: null },
  { label: "1600s", value: "1600s" },
  { label: "1700s", value: "1700s" },
  { label: "1800s", value: "1800s" },
  { label: "1900s", value: "1900s" },
  { label: "2000s", value: "2000s" },
] as const;
